<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.eyecool</groupId>
        <artifactId>eyecool-biapwp</artifactId>
        <version>${eyecool.version}</version>
    </parent>
    <artifactId>eyecool-biapwp-visitor</artifactId>
    <dependencies>

        <!-- 通用工具 -->
        <dependency>
            <groupId>cn.eyecool</groupId>
            <artifactId>eyecool-biapwp-common</artifactId>
        </dependency>

        <!--短信模块-->
        <dependency>
            <groupId>cn.eyecool</groupId>
            <artifactId>eyecool-biapwp-msg</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.eyecool</groupId>
            <artifactId>eyecool-biapwp-basedata</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.eyecool</groupId>
            <artifactId>eyecool-biapwp-adapter</artifactId>
        </dependency>

    </dependencies>


</project>